server:
  port: 9999
  context-path: /uaa

security:
  sessions: if-required
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: auth
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
