spring:
  application:
    name: zia-auth
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: ${port:9999}
  context-path: /uaa

security:
  sessions: if-required

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka