spring:
  application:
    name: spring-boot-admin

security:
  user:
    name: test
    password: test

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: false